# Generated by Django 2.1.1 on 2019-02-13 10:37

from django.db import migrations, models
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICCharger',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_charge_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCard',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('balance', models.IntegerField()),
                ('icon', stdimage.models.StdImageField(upload_to='images/')),
                ('bio', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TopUpHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=7)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance', models.IntegerField()),
                ('top_up_money', models.IntegerField()),
            ],
        ),
    ]
